name: Check github action

on: workflow_call

jobs:
  linting:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@5c140f8fcd4035d84e5d893f1e4a9dc1283e1e4a # v4.0.1
        with:
          aqua_version: v2.53.3
      - name: Lint github actions
        run: |
          actionlint -color
          ghalint run
